version: '3'
services:
  redis-master:
    container_name: redis-master
    image: redis:7
    command: redis-server --appendonly yes --requirepass password
    ports:
      - "6379:6379"
    networks:
      - redis-replication
    volumes:
      - ./data:/data

  redis-slave1:
    container_name: "redis-slave1"
    image: redis:7
    ports:
      - "6380:6379"
    command: redis-server /etc/redis.conf --replicaof redis-master 6379 --requirepass password
    depends_on:
      - redis-master
    volumes:
      - ./redis.conf:/etc/redis.conf
    networks:
      - redis-replication

  redis-slave2:
    container_name: "redis-slave2"
    image: redis:7
    ports:
      - "6381:6379"
    command: redis-server /etc/redis.conf --replicaof redis-master 6379 --requirepass password
    depends_on:
      - redis-master
    volumes:
      - ./redis.conf:/etc/redis.conf
    networks:
      - redis-replication

  redis-sentinel:
    container_name: 'redis-sentinel'
    image: redis:7
    ports:
      - "5000:5000"
    command: redis-sentinel /etc/sentinel.conf --requirepass password
    volumes:
      - ./sentinel/sentinel.conf:/etc/sentinel.conf
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2

networks:
  redis-replication:
    driver: bridge
